### ISSUE TITLE
numpy<1.26 requirement breaks python 3.12 compatibility 

### ISSUE THREAD

**Issue by chrisbennight** [rhasspy/pysilero-vad#3]
numpy<1.26 is in the requirements.txt, but numpy requires version >= 1.26 to work on python 3.12 - ref:  https://github.com/numpy/numpy/issues/23808#issuecomment-1722440746

does something here break with numpy >= 1.26, or was this just a defensive version comstraint?

**Comment by synesthesiam** [comment]
Defensive. At the time, 1.26 was out but the wheels weren't available for arm32 yet so it was forcing devices to build numpy from source.
It looks like 1.26 is supported now, so the requirements can be bumped to < 2.
