### ISSUE TITLE
Trying to build  wyoming app using v2 on linux/arm/v7 (32 bit pi os), cannot find onnxruntime, but not using

### ISSUE THREAD

**Issue by sdetweil** [rhasspy/pysilero-vad#4]
project here https://github.com/sdetweil/wyoming-sonus

run script/build_docker

via requirements.txt 
wyoming==1.6.0
zeroconf==0.88.0
pyring-buffer==1.0.0
pysilero-vad==2.0.0

.6 INFO: pip is looking at multiple versions of pysilero-vad to determine which version is compatible with other requirements. This could take a while.
145.6 ERROR: Could not find a version that satisfies the requirement onnxruntime<2,>=1.18.0 (from pysilero-vad) (from versions: none)
146.5 ERROR: No matching distribution found for onnxruntime<2,>=1.18.0

**Comment by sdetweil** [comment]
also, now get  runtime error on V2 (diff from V1) 

code
```python
        chunk = AudioChunk.from_event(event)

        audio_bytes = chunk.audio
        sound_heard = self.vad(audio_bytes)
```
```text
 |   File "/app/.venv/lib/python3.11/site-packages/pysilero_vad/__init__.py", line 63, in __call__
sonus_1            |     return self.process_chunk(audio)
sonus_1            |            ^^^^^^^^^^^^^^^^^^^^^^^^^
sonus_1            |   File "/app/.venv/lib/python3.11/site-packages/pysilero_vad/__init__.py", line 72, in process_chunk
sonus_1            |     raise InvalidChunkSizeError
sonus_1            | pysilero_vad.InvalidChunkSizeError
```

copied from wyoming satellite (satellite using V1, I was using V1, but need to fix the onnx runtime problem)
```
        self.vad = SileroVad(
            threshold=self.config_info['vad']['threshold'], trigger_level=self.config_info['vad']['trigger_level']
        )
```
satellite
```
        self.vad = SileroVad(
            threshold=settings.vad.threshold, trigger_level=settings.vad.trigger_level
        )
```

**Comment by synesthesiam** [comment]
Microsoft does not provide 32-bit builds of onnxruntime, and I've been unable to build it in the last year or two ☹️

**Comment by sdetweil** [comment]
bummer..
